# Generated by Django 3.2.5 on 2022-03-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=255, null=True)),
                ('item_description', models.CharField(blank=True, max_length=255, null=True)),
                ('item_price', models.IntegerField()),
            ],
        ),
    ]
