# Generated by Django 3.2.5 on 2022-03-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='item_image',
            field=models.CharField(default='https://media.istockphoto.com/vectors/fast-food-vector-card-with-text-placeholder-vector-frame-with-fast-vector-id1131995796', max_length=555),
        ),
    ]
